name: Run bot

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "user_interface.py"
  schedule:
    - cron: "1 */5 * * *"

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Python Dependency Installation
        uses: py-actions/py-dependency-install@v4.1.0

      - name: Injection For my Repo
        run: sed -i "s/TokenTimeIsBackBuddyss/${{ secrets.LICHESS_KEY }}/g" config.yml

      - name: Restore last run cache
        id: cache
        uses: actions/cache@v4
        with:
          path: .last_run_matchmaking
          key: last-bot-run-marker

      - name: Stockfish
        run: |
          chmod +x ./engines/stockfish

      - name: Decide and run the bot
        run: |
          if [ -f .last_run_matchmaking ]; then
            echo "Running: python -u user_interface.py"
            python -u user_interface.py
            rm -f .last_run_matchmaking
          else
            echo "Running: python -u user_interface.py --matchmaking"
            python -u user_interface.py --matchmaking
            touch .last_run_matchmaking
          fi

      - name: Save last run cache
        uses: actions/cache@v4
        with:
          path: .last_run_matchmaking
          key: last-bot-run-marker
